name: rialto_viewer
description: The Rialto Point Cloud Viewer
dependencies:
  barback: any
  browser: any
  core_elements: any
  crypto: any
  http: any
  paper_elements: any
  polymer: any
  shelf_web_socket: any
  three:
    git: https://github.com/threedart/three.dart
  vector_math: any
transformers:
- rialto_viewer
- polymer
